### ISSUE TITLE
chapter2: 打卡记录

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#12]

**Comment by BugZheng** [comment]
https://github.com/Jony-J/CSAPP-READ/blob/master/chapter-2.md

**Comment by 0XFF-96** [comment]
打卡 https://github.com/Alex1996a/golang-snippet/issues/21

**Comment by SHenry07** [comment]
https://github.com/SHenry07/roadmap/blob/master/computer/csapp/basic.md#%E7%AC%AC%E4%BA%8C%E5%91%A8

**Comment by chensongbin** [comment]
第二周打卡 https://www.notion.so/Summary-fae85e19a7d74938872bfd800d703b60

**Comment by 0XFF-96** [comment]
肖思成：https://talkgo.org/t/topic/1022/10

**Comment by 0XFF-96** [comment]
王传义： 
![Uploading 4361601207166_.pic_hd.jpg…]()

https://talkgo.org/t/topic/1022/9
