### ISSUE TITLE
(2u-4u) 无符号数减法运算是如何实现的？

### ISSUE THREAD

**Issue by chensongbin** [Talk-Go-CSAPP-05/Discusion#13]
一、假设w=4
2u  =  [0010]
4u  =  [0100]

二、大胆猜想：
(1)编码
2u = [0010]
-4 = [1100]
(2)执行加法
[0010] + [1100] = [1110] = 13

三、验证思路：
写代码
```
// w=8
uint8 a = 2
uint8 b = 4
unit8 c = a - b 
```
反汇编，分析汇编代码

四、结论
TODO

**Comment by SHenry07** [comment]
16进制是一样的。
> https://www.zhihu.com/question/51493338

**Comment by chensongbin** [comment]
写了一份调研文档，欢迎大家评论
https://www.notion.so/197d5e10f32a479eb40bd21e9b4566bb
