### ISSUE TITLE
确定本月讨论会-deadline-10-25

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#15]
### 讨论会议

- 讨论会投票提案截止时间：10-25 号
- 讨论会投票截止时间：10-25 号
- 讨论会开始时间： 10-31  号

> 请大家集思广益

**Comment by 0XFF-96** [comment]
### 选题一：汇编学习过程中的一些坑

**Comment by 0XFF-96** [comment]
### 选题二： 关于内存对齐

**Comment by 0XFF-96** [comment]
### 选题三：大家把本章所学做个总结

**Comment by SHenry07** [comment]
> ### 选题三：大家把本章所学做个总结
我个人除了对寄存器 状态位等有了些了解，更多的是对gdb的使用 多了些实践

**Comment by 0XFF-96** [comment]
已经确定：选择关于内存对齐的相关知识进行分享。
