### ISSUE TITLE
第三周作业打卡

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#16]
### 打卡形式

请大家先自行到这个帖子上发贴打卡，然后将链接发给我检查一下： https://talkgo.org/t/topic/1064/5

**Comment by SHenry07** [comment]
https://github.com/SHenry07/roadmap/blob/master/computer/csapp/basic.md#%E7%AC%AC%E4%B8%89%E5%91%A8

**Comment by BugZheng** [comment]
https://github.com/Jony-J/CSAPP-READ/blob/master/chapter-3

**Comment by watchpoints** [comment]
第三周打卡:https://github.com/wangcy6/weekly_read/tree/master/book/CSAPP

> 实验1：通过GDB调试一个简单函数调用c代码，看懂一个函数汇代码和16个寄存器如何被执行的。

- 如果既想显示源代码，又想显示汇编代码，可以使用“layout split”命令
- 继续补充：https://github.com/Talk-Go-CSAPP-05/Discusion/issues/14

64 位 | 32 位 | 16 位 | 8 位 | 职责
-- | -- | -- | -- | --
%rax | %eax | %ax | %al | 返回值
%rbx | %ebx | %bx | %bl | 被调用者保存
%rcx | %ecx | %cx | %cl | 第四个参数
%rdx | %edx | %dx | %dl | 第三个参数
%rsi | %esi | %si | %sil | 第二个参数
%rdi | %edi | %di | %dil | 第一个参数
%rbp | %ebp | %bp | %bpl | 帧指针
%rsp | %esp | %sp | %spl | 栈指针
%r8 | %r8d | %r8w | %r8b | 第五个参数
%r9 | %r9d | %r9w | %r9b | 第六个参数
%r10 | %r10d | %r10w | %r10b | 调用者保存
%r11 | %r11d | %r11w | %r11b | 调用者保存
%r12 | %r12d | %r12w | %r12b | 被调用者保存
%r13 | %r13d | %r13w | %b13b | 被调用者保存
%r14 | %r14d | %r14w | %r14b | 被调用者保存
%r15 | %r15d | %r15w | %r15b | 被调用者保存

**Comment by chensongbin** [comment]
第三周打卡 3.1 ～ 3.7
https://www.notion.so/Summary-fae85e19a7d74938872bfd800d703b60

打卡链接
https://talkgo.org/t/topic/1064/30

**Comment by gewuang** [comment]
第三周打卡：https://talkgo.org/t/topic/1064/50
