### ISSUE TITLE
第四周打卡贴

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#18]

**Comment by BugZheng** [comment]
https://github.com/Jony-J/CSAPP-READ/blob/master/chapter-4.md
https://github.com/Jony-J/CSAPP-READ/blob/master/chapter-3

**Comment by chensongbin** [comment]
talkgo:  https://talkgo.org/t/topic/1136/10

notion: https://www.notion.so/Summary-fae85e19a7d74938872bfd800d703b60

**Comment by watchpoints** [comment]
第四周打卡:https://github.com/wangcy6/weekly_read/tree/master/book/CSAPP
> 继续 实验1：通过GDB调试一个简单函数调用c代码，看懂一个函数汇代码和16个寄存器如何被执行的。

- 函数A调用函数B过程参数传递与寄存器关系[3.7章节]

- 栈作用：保存参数（大于6个），局部变量（寄存器），函数调用关系

- 看golang夜读汇编函数A调用函数B,需要保持函数A返回地址。

- FQA：https://github.com/Talk-Go-CSAPP-05/Discusion/issues/14

**Comment by gewuang** [comment]
所在小组

第五组

组内昵称

张学广

心得体会

一个处理器支持的指令和指令的字节级编码成为它的指令集体系结构ISA，第四章围绕ISA的指令的介绍为我们打开计算机是如何工作的大门，解释第三章的指令是如何运行的。

本章重点如下：

- 简单的逻辑电路如何组合实现重要的ALU逻辑单元以及寄存器等
- 指令执行的五个阶段（取值、译码、执指、访存、写回）的实现
- 流水线的实现（可以同时有五个在不同状态进行中）
- 流水线遇到的问题（数据&控制）以及如何解决

个人总结：

如果说上一章为我们揭开了代码是如何转换成汇编语言这种计算机能理解的语言的话，这一章为我们展示了汇编指令是如何在处理器中执行的，简单的逻辑门组合成功能强大的组合电路是我在本章感觉很神奇的地方，想起了之前没看完的《编码》，可以安排起来了，之后的流水线部分从操作系统课里面的几句话变成了具体的实现，还是挺有感慨的，不过基本很少接触，所以没有细读。

talkgo: https://talkgo.org/t/topic/1136/25

**Comment by 0XFF-96** [comment]
https://talkgo.org/t/topic/1136/14
