### ISSUE TITLE
第五周打卡贴

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#19]

**Comment by BugZheng** [comment]
https://github.com/Jony-J/CSAPP-READ/blob/master/chapter-6.md

**Comment by SHenry07** [comment]
https://talkgo.org/t/topic/1196/4

**Comment by watchpoints** [comment]
https://talkgo.org/t/topic/1196/5

**Comment by chensongbin** [comment]
https://talkgo.org/t/topic/1196/11

**Comment by 0XFF-96** [comment]
https://talkgo.org/t/topic/1196/26 肖思成

**Comment by gewuang** [comment]
张学广 https://talkgo.org/t/topic/1196/35
