### ISSUE TITLE
确定本月讨论会的主题？

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#2]

**Comment by 0XFF-96** [comment]
### 提议1: 我们本月的讨论会，围绕**进程** 这个相关的概念进程如何？

**Comment by SHenry07** [comment]
> 提议1: 我们本月的讨论会，围绕**进程** 这个相关的概念进程如何？

可能到后面的章节会有更好地理解吧

**Comment by 0XFF-96** [comment]
### 提议2: 如何更好地学习这本书，有什么经验方法分享？

**Comment by chensongbin** [comment]
### 提议3: 为什么系统开销那么大？ 
### 提议4: 为什么用补码表示有符号数？

**Comment by SHenry07** [comment]
> ### 提议4: 为什么用补码表示有符号数？
uint 直接用的二进制， 那么补码 two's complement 就是多了符号位的概念。 你是想讨论补码效率高吗？

**Comment by chensongbin** [comment]
> > ### 提议4: 为什么用补码表示有符号数？
> 
> uint 直接用的二进制， 那么补码 two's complement 就是多了符号位的概念。 你是想讨论补码效率高吗？


1. 我觉得讨论效率是一方面。结论 效率高是一定的，如果有更好的肯定不会选补码是吧
2. 讨论这个 主要是让我们回到最开始的时代 我们可以通过讨论 走一走 前辈们走的路 是经过怎样的思考 最后确认了补码这种方式
3. 而且我希望这是一个引子 在讨论中 能够拓展出更多有趣的问题

**Comment by 0XFF-96** [comment]
### 提议5： 乘法和 除法在机器级是如何表示的

**Comment by 0XFF-96** [comment]
> ### 提议1: 我们本月的讨论会，围绕**进程** 这个相关的概念进程如何？

这个确实后面讨论会更好

**Comment by watchpoints** [comment]
抽象和分层设计，操作系统精髓。

**Comment by SHenry07** [comment]
> * 我觉得讨论效率是一方面。结论 效率高是一定的，如果有更好的肯定不会选补码是吧
> * 讨论这个 主要是让我们回到最开始的时代 我们可以通过讨论 走一走 前辈们走的路 是经过怎样的思考 最后确认了补码这种方式
> * 而且我希望这是一个引子 在讨论中 能够拓展出更多有趣的问题

![image](https://user-images.githubusercontent.com/39635430/94413703-041ed980-01ae-11eb-9469-6721d2849c7f.png)

主要是0的表示的考量吧

**Comment by chensongbin** [comment]
> > * 我觉得讨论效率是一方面。结论 效率高是一定的，如果有更好的肯定不会选补码是吧
> > * 讨论这个 主要是让我们回到最开始的时代 我们可以通过讨论 走一走 前辈们走的路 是经过怎样的思考 最后确认了补码这种方式
> > * 而且我希望这是一个引子 在讨论中 能够拓展出更多有趣的问题
> 
> ![image](https://user-images.githubusercontent.com/39635430/94413703-041ed980-01ae-11eb-9469-6721d2849c7f.png)
> 
> 主要是0的表示的考量吧

我查资料了解到还有一个使用补码的好处：
比如计算两个数相加，使用补码，符号位跟数值一样直接相加 溢出了就进1

用其他方式，符号位的处理可能就要单独处理：
