### ISSUE TITLE
关于 objdump 的使用疑惑

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#20]
### 下面两条命令输出的汇编代码的区别是什么？
- 1、objdump -d XX.o  
- 2、 obidump -d XX

> by 孙恒

**Comment by SHenry07** [comment]
可执行文件 与 可重定位目标文件
> 见P465 csapp 第7章

一个是程序，一个是代码片段
一个是所有函数的汇编代码，一个是部分函数的汇编代码
