### ISSUE TITLE
第六周打卡贴

### ISSUE THREAD

**Issue by 0XFF-96** [Talk-Go-CSAPP-05/Discusion#22]

**Comment by watchpoints** [comment]
https://talkgo.org/t/topic/1221/31

**Comment by gewuang** [comment]
张学广

第六章 存储器层次结构
这一章介绍了计算机中的各种存储器，以及各自的优缺点和组合使用，之后介绍了如何编写缓存友好的代码，在这部分有很好的收货。
计算机中的存储是分层的，从最高速的cpu缓存，到 L1、L2、L3这些高速缓存，之后是主存以及最后的磁盘存储，规律是存储从小到大，速度从快到慢，造价从高到底，这样的组合利用了各种存储器的优劣势可以兼顾速度大小与造价。
之后是些高速缓存友好的代码，有以下几点
1. 让常见的情况运行的更快
2. 尽量增加缓存命中
到实际中需要注意的两点：
1. 对局部变量反复利用
2. 步长为1的引用模式
命中率主要看高速缓存的原理，一行一行的读取数据是要比一列一列读取快的多的。
其次也要注意程序的切换，切换程序会导致缓存的刷新，导致命中率降低

**Comment by SHenry07** [comment]
https://talkgo.org/t/topic/1221/44

**Comment by chensongbin** [comment]
https://talkgo.org/t/topic/1221/52
