### ISSUE TITLE
什么是进程？进程是如何被抽象成一个具体的概念的？（when、why、how) 

### ISSUE THREAD

**Issue by SHenry07** [Talk-Go-CSAPP-05/Discusion#7]
进程是代码动态执行过程的抽象，
进程就是地址空间，然后系统完成对上下文切换调度完成并发执行。
>王传义_济南

**Comment by SHenry07** [comment]
程序: 为完成特定功能，用某种计算机语言编写的一组指令的集合
进程: 进行--过程
   - 是程序/代码的一次执行过程
   - 是系统进行资源分配和调度的一个独立单位
进程和程序/代码的区别
- 进程是动态的(暂时), 程序是静态的(永久)
- 程序的每次执行构成不同的进程，一个程序可以对应多个进程

进程的特征：
- 动态性 -- 有生命周期
由创建而产生，由调度而执行，由等待而暂停(等待某种资源，等待I/O完成)，因完成而消亡
- 独立性： 是系统进行资源分配和调度的一个独立单位
- 并发性： 
- 异步性：每个进程都以自己独立的，不可预知的速度进展。(不可再现性)
> 摘自<<计算机导论>>
- 结构性：每个进程都会配置一个PCB,结构上看，进程由程序段，数据段，PCB组成
> 《王道考研》

**Comment by 0XFF-96** [comment]
理解1:
```
是的，有不同的理解方法。不同书本的定义也不同。
在上面我学到的是，进程是在多道程序技术出现后，为了方便操作系统，解决各种资源的并发访问，而引出的一个概念。 
```


理解2:
```
以前IBM统治时代叫任务，后人改名进程！
```

理解3:

```
我个人觉得理解成 内核维护的一个数据结构  感觉进程的定义都太抽象了 最好能够结合进程的实现来理解
```

理解4:
```
进程的数据结构是双向链表
```




PS: 上面都是大家在微信群讨论的总结

**Comment by 0XFF-96** [comment]
什么是进程， 进程是如何被抽象成一个具体的概念的？（when、why、how)
